version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5431:5432
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && yarn install --check-files && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - bundle_path:/usr/local/bundle:cached
      - .:/myapp:cached
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  bundle_path:
  db_data:
